name: CI (Build • Test • Lint • Publish)

on:
  push:
  pull_request:


env:
  APP_PORT: 4499
  IMAGE_NAME: ghcr.io/${{ github.repository_owner.toLowerCase() }}/wisecow


jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write         # needed only if we push to GHCR on main
      security-events: write  # future-proof if you upload code scanning later

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Hadolint is NON-BLOCKING: it will never fail the job
      - name: Lint Dockerfile (Hadolint, non-blocking)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: tty
          failure-threshold: error   # only "error" would count…
          no-fail: true              # …but we still never fail the job
        continue-on-error: true      # double safety

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load locally for tests)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          load: true                       # makes the image available to "docker run"
          push: false
          tags: ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}

      - name: Run container
        run: |
          docker run -d --rm \
            --name wisecow_ci \
            -p $APP_PORT:$APP_PORT \
            ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}
          # wait up to ~20s for the app to respond
          for i in {1..20}; do
            if curl -fsS http://127.0.0.1:${APP_PORT}/ >/dev/null; then
              echo "✅ App responded on ${APP_PORT}"
              exit 0
            fi
            sleep 1
          done
          echo "❌ App did not respond on ${APP_PORT}"
          docker logs wisecow_ci || true
          exit 1

      - name: Stop container
        if: always()
        run: docker rm -f wisecow_ci || true

      # Publish to GHCR only on pushes to main
      - name: Log in to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR (latest + sha)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

