name: CI Build & Publish (Wisecow)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: 4499

    steps:
      - name: Lowercase image owner
        id: lowercase
        run: echo "IMAGE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Define image name
        run: echo "IMAGE_NAME=ghcr.io/${IMAGE_OWNER}/wisecow" >> $GITHUB_ENV

      - name: Show vars
        run: |
          echo "Using image: $IMAGE_NAME"
          echo "Port: $APP_PORT"

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push on PR)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: "${{ env.IMAGE_NAME }}:ci-${{ github.sha }}"
